### PR TITLE
Sitemap images

### PR DESCRIPTION
**Pull request by simaodeveloper**
I created a mode to generate sitemap for images per page, we just need to add `images: true` at options and this is it! If it's be helpful tell me

### CODE REVIEW

**Comment by pgilad** [comment]
Looks good! I'll review it tonight 👍

**Comment by pgilad** [comment]
Awesome work 🏆

**Comment by simaodeveloper** [comment]
Thanks man! 👍

**Comment by simaodeveloper** [comment]
@pgilad When the next release go out?

**Comment by pgilad** [comment]
https://github.com/pgilad/gulp-sitemap/releases/tag/v7.0.0

**Pull request merged**
