### PR TITLE
Allow lastmod to be a command that is executed for the current entry

### PR DESCRIPTION
**Pull request by Frank3K**
Implements #12.

Could you please review @pgilad?

I'm not sure about the API. Now, it is detected whether the current `lastmod` string is a date or not. If it's not, it's assumed to be a command. Would it be better to add a property like e.g. `lastmodcmd`?

### CODE REVIEW

**Comment by Frank3K** [comment]
I was thinking `$1` would better be changed to a more meaningful name, in case (some time in the future) extra parameters would be added.

**Comment by Frank3K** [comment]
Updated PR with suggestions made by @alethea. I think it's significantly better than before now.

@pgilad: can you review? I will rebase when it's complete.

**Comment by alethea** [comment]
I like this approach!

**Comment by pgilad** [comment]
So the selected approach is that the function for getting mtime of a file is always sync?

**Comment by Frank3K** [comment]
Sync does the job and is in line with e.g. `getLoc()`. Furthermore I think the sync approach needs a lot less changes to the existing codebase than an async approach (although I'm not sure how to do async properly). 

Should I rebase now or do you have suggestions for changes?

**Comment by pgilad** [comment]
You don't need to rebase, I'll do it with the merge, still need to review this :-)

**Pull request closed without merging**
